FROM microsoft/aspnetcore
WORKDIR /vsdbg
RUN  apt-get update \ 
     && apt-get clean \
     && apt-get install -y --no-install-recommends unzip \
     && rm -rf /var/lib/apt/lists/* \
     && curl -sSL http://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg
WORKDIR /app
ENTRYPOINT ["tail", "-f", "/dev/null"]
    