version: "2"

services:
  build:
    image: microsoft/aspnetcore-build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "npm install && dotnet restore && dotnet publish react-dotnetcore2.csproj -c Release -o ./obj/Docker/publish" 

